
// Code generated by protoc-gen-vison.
// versions: 
// protoc-gen-vison v1.0.0

package flow_log

import (
	context "context"

	pb "github.com/visonlv/protoc-gen-vison/proto/demo"
)

type FlowLogService struct {
}

func (the *FlowLogService) Page(ctx context.Context, req *pb.FlowLogPageReq, resp *pb.FlowLogPageResp) error {
	return nil
}


func (the *FlowLogService) ExportPage(ctx context.Context, req *pb.FlowLogExportPageReq, resp *pb.FlowLogExportPageResp) error {
	return nil
}


func (the *FlowLogService) GetStream(ctx context.Context, s *pb.FlowLogService_GetStreamServer) error {
	return nil
}


func (the *FlowLogService) PutStream(ctx context.Context, req *pb.StreamReqData, s *pb.FlowLogService_PutStreamServer) error {
	return nil
}


func (the *FlowLogService) AllStream(ctx context.Context, s *pb.FlowLogService_AllStreamServer) error {
	return nil
}

