// Code generated by protoc-gen-infore.
// versions: 
// protoc-gen-infore v1.0.0

package flow_log

import (
	context "context"

	pb "github.com/visonlv/protoc-gen-vison/proto/demo"
)

type FlowLogService struct {
}

func (the *FlowLogService) Page(ctx context.Context, req *pb.FlowLogPageReq, resp *pb.FlowLogPageResp) error {
	return nil
}

func (the *FlowLogService) ExportPage(ctx context.Context, req *pb.FlowLogExportPageReq, resp *pb.FlowLogExportPageResp) error {
	return nil
}
