// Code generated by protoc-gen-infore. DO NOT EDIT.
// versions: 
// protoc-gen-infore v1.0.0

package demo

import (
	context "context"

	"google.golang.org/grpc"
)

type FlowLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func (c *FlowLogServiceClient) Page(ctx context.Context, in *FlowLogPageReq, opts ...grpc.CallOption) (*FlowLogPageResp, error) {
	out := new(FlowLogPageResp)
	err := c.cc.Invoke(ctx, "/rpc/speech/FlowLog.Page", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *FlowLogServiceClient) ExportPage(ctx context.Context, in *FlowLogExportPageReq, opts ...grpc.CallOption) (*FlowLogExportPageResp, error) {
	out := new(FlowLogExportPageResp)
	err := c.cc.Invoke(ctx, "/rpc/speech/FlowLog.ExportPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func NewFlowLogServiceClient(cc grpc.ClientConnInterface) *FlowLogServiceClient {
	return &FlowLogServiceClient{cc}
}

type DemoClient struct {
	FlowLogService   *FlowLogServiceClient
	
}

func NewDemoClient(cc grpc.ClientConnInterface) *DemoClient {
	client := &DemoClient{}
	client.FlowLogService = &FlowLogServiceClient{cc}
	
	return client
}
