// Code generated by protoc-gen-vison.
// versions: 
// protoc-gen-vison v1.0.0

package handler

import (
	flow_log_handler "github.com/visonlv/protoc-gen-vison/handler/flow_log"
	
)

func GetLsit() []interface{} {
	list := make([]interface{}, 0)
	list = append(list, &flow_log_handler.FlowLogService{})
	
	return list
}

func GetUrlMap() map[string]string {
	urls := make(map[string]string)
	urls["FlowLogService.Page"] = "/rpc/speech/FlowLog.Page"
	urls["FlowLogService.ExportPage"] = "/rpc/speech/FlowLog.ExportPage"
	
	return urls
}
