
// Code generated by protoc-gen-vison.
// versions: 
// protoc-gen-vison v1.0.0

package handler

import (
	flow_log_handler "github.com/visonlv/protoc-gen-vison/handler/flow_log"
	
)

func GetLsit() []interface{} {
	list := make([]interface{}, 0)
	list = append(list, &flow_log_handler.FlowLogService{})
	
	return list
}

func GetUrlMap() map[string][]string {
	methodDescMap := make(map[string][]string)
	methodDescMap["FlowLogService.Page"] = []string{"/rpc/speech/FlowLog.Page", "false", "false"}
	methodDescMap["FlowLogService.ExportPage"] = []string{"/rpc/speech/FlowLog.ExportPage", "false", "false"}
	methodDescMap["FlowLogService.GetStream"] = []string{"/rpc/speech/stream.get", "false", "true"}
	methodDescMap["FlowLogService.PutStream"] = []string{"/rpc/speech/stream.put", "true", "false"}
	methodDescMap["FlowLogService.AllStream"] = []string{"/rpc/speech/stream.all", "true", "true"}
	
	return methodDescMap
}
