package gen_proto

import (
	"bytes"
	"fmt"
	"os"

	"github.com/visonlv/protoc-gen-vison/logger"
	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

func GenerateClient(plugin *protogen.Plugin, serverName string) error {
	fileFullPath := serverName + "/client.go"
	fileWriter, err := os.OpenFile(fileFullPath, os.O_CREATE|os.O_RDWR|os.O_TRUNC, 0644)
	if err != nil {
		logger.Infof("open file:%s failed, err:%s", fileFullPath, err)
		return nil
	}
	defer fileWriter.Close()

	WriteLine(fileWriter, "// Code generated by protoc-gen-infore. DO NOT EDIT.")
	WriteLine(fileWriter, "// versions: ")
	WriteLine(fileWriter, fmt.Sprintf("// protoc-gen-infore %s", "v1.0.0"))
	WriteLine(fileWriter)
	WriteLine(fileWriter, "package ", serverName)
	WriteLine(fileWriter, `
import (
	context "context"

	"google.golang.org/grpc"
)`)

	var clientBuf bytes.Buffer
	var newClientBuf bytes.Buffer
	for _, file := range plugin.Files {
		if len(file.Services) == 0 {
			continue
		}

		for _, service := range file.Services {
			clientBuf.Write([]byte(fmt.Sprintf("%s   *%sClient\n\t", service.GoName, service.GoName)))
			newClientBuf.Write([]byte(fmt.Sprintf("client.%s = &%sClient{cc}\n\t", service.GoName, service.GoName)))

			WriteLine(fileWriter, fmt.Sprintf(`
type %sClient struct {
	cc grpc.ClientConnInterface
}`, service.GoName))
			sd := &serviceDesc{
				ServiceType: service.GoName,
				ServiceName: string(service.Desc.FullName()),
				Metadata:    file.Desc.Path(),
			}
			for _, method := range service.Methods {
				if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
					continue
				}
				rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
				var methodDesc *methodDesc
				if rule != nil && ok {
					methodDesc = buildHTTPRule(serverName, method, rule)
				} else {
					path := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
					methodDesc = buildMethodDesc(serverName, method, "POST", path)
				}
				sd.Methods = append(sd.Methods, methodDesc)

				WriteLine(fileWriter, fmt.Sprintf(`
func (c *%sClient) %s(ctx context.Context, in *%s, opts ...grpc.CallOption) (*%s, error) {
	out := new(%s)
	err := c.cc.Invoke(ctx, "%s", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}`, service.GoName, methodDesc.Name, methodDesc.Request, methodDesc.Reply, methodDesc.Reply, methodDesc.Path))
			}

			WriteLine(fileWriter, fmt.Sprintf(`
func New%sClient(cc grpc.ClientConnInterface) *%sClient {
	return &%sClient{cc}
}`, service.GoName, service.GoName, service.GoName))
		}
	}

	camelName := camelCase(serverName)
	WriteLine(fileWriter, fmt.Sprintf(`
type %sClient struct {
	%s
}`, camelName, clientBuf.String()))

	WriteLine(fileWriter, fmt.Sprintf(`
func New%sClient(cc grpc.ClientConnInterface) *%sClient {
	client := &%sClient{}
	%s
	return client
}`, camelName, camelName, camelName, newClientBuf.String()))

	fileWriter.Close()
	return nil
}
