package gen_proto

var versionName = `
// Code generated by protoc-gen-vison.
// versions: 
// protoc-gen-vison v1.0.0
`

var normalClientFunc = `
func (c *${serviceName}Client) ${methodName}(ctx context.Context, in *${req}, opts ...grpc.CallOption) (*${resp}, error) {
	out := new(${resp})
	err := c.cc.Invoke(ctx, "${methodPath}", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
`
var allStreamClient = `
type ${serviceName}_${methodName}Client struct {
	grpc.ClientStream
}

func (x *${serviceName}_${methodName}Client) Send(m *${req}) error {
	return x.ClientStream.SendMsg(m)
}

func (x *${serviceName}_${methodName}Client) Recv() (*${resp}, error) {
	m := new(${resp})
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
`
var allStreamClientFunc = `
func (c *${serviceName}Client) ${methodName}(ctx context.Context, opts ...grpc.CallOption) (*${serviceName}_${methodName}Client, error) {
	stream, err := c.cc.NewStream(ctx, &grpc.StreamDesc{
		StreamName: "${methodName}", ServerStreams: true, ClientStreams: true}, "${methodPath}", opts...)
	if err != nil {
		return nil, err
	}
	x := &${serviceName}_${methodName}Client{stream}
	return x, nil
}
`

var clientStreamClient = `
type ${serviceName}_${methodName}Client struct {
	grpc.ClientStream
}

func (x *${serviceName}_${methodName}Client) Recv() (*${resp}, error) {
	m := new(${resp})
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}`

var clientStreamClientFunc = `
func (c *${serviceName}Client) ${methodName}(ctx context.Context, in *${req}, opts ...grpc.CallOption) (*${serviceName}_${methodName}Client, error) {
	stream, err := c.cc.NewStream(ctx, &grpc.StreamDesc{
		StreamName: "${methodName}", ClientStreams: true}, "${methodPath}", opts...)
	if err != nil {
		return nil, err
	}
	x := &${serviceName}_${methodName}Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}
`

var serverStreamClient = `
type ${serviceName}_${methodName}Client struct {
	grpc.ClientStream
}

func (x *${serviceName}_${methodName}Client) Send(m *${req}) error {
	return x.ClientStream.SendMsg(m)
}

func (x *${serviceName}_${methodName}Client) CloseAndRecv() (*${resp}, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(${resp})
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
`

var serverStreamClientFunc = `
func (c *${serviceName}Client) ${methodName}(ctx context.Context, opts ...grpc.CallOption) (*${serviceName}_${methodName}Client, error) {
	stream, err := c.cc.NewStream(ctx, &grpc.StreamDesc{
		StreamName: "${methodName}", ServerStreams: true}, "${methodPath}", opts...)
	if err != nil {
		return nil, err
	}
	x := &${serviceName}_${methodName}Client{stream}
	return x, nil
}`

var allStreamServer = `
type ${serviceName}_${methodName}Server struct {
	grpc.ServerStream
}

func (x *${serviceName}_${methodName}Server) Send(m *${resp}) error {
	return x.ServerStream.SendMsg(m)
}

func (x *${serviceName}_${methodName}Server) Recv() (*${req}, error) {
	m := new(${req})
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
`

var allStreamServerFunc = `
func (the *${serviceName}) ${methodName}(ctx context.Context, s *pb.${serviceName}_${methodName}Server) error {
	return nil
}
`

var serverStreamServer = `
type ${serviceName}_${methodName}Server struct {
	grpc.ServerStream
}

func (x *${serviceName}_${methodName}Server) SendAndClose(m *${resp}) error {
	return x.ServerStream.SendMsg(m)
}

func (x *${serviceName}_${methodName}Server) Recv() (*${req}, error) {
	m := new(${req})
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
`

var serverStreamServerFunc = `
func (the *${serviceName}) ${methodName}(ctx context.Context, s *pb.${serviceName}_${methodName}Server) error {
	return nil
}
`

var clientStreamServer = `
type ${serviceName}_${methodName}Server struct {
	grpc.ServerStream
}

func (x *${serviceName}_${methodName}Server) Send(m *${resp}) error {
	return x.ServerStream.SendMsg(m)
}
`

var clientStreamServerFunc = `
func (the *${serviceName}) ${methodName}(ctx context.Context, req *pb.${req}, s *pb.${serviceName}_${methodName}Server) error {
	return nil
}
`

var nolmalServer = `
func (the *${serviceName}) ${methodName}(ctx context.Context, req *pb.${req}, resp *pb.${resp}) error {
	return nil
}
`
